apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: nginx-test
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        —name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim
      containers:
       —name: nginx
          image: nginx
          resources:
            limits:
              memory: 200M
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
           —containerPort: 80
          volumeMounts:
            —mountPath: "/usr/share/nginx/html"
             name: nginx-pv-claim
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: nginx-test
spec:
  ingressClassName: nginx
  rules:
    - host: web.ceres.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
             
