apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
       —name: nginx
          image: nginx
          resources:
            limits:
              memory: 200M
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
           —containerPort: 80
